// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/config.post').default>>>>
    }
    '/api/admin/templates/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/templates/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/templates/[id].put').default>>>>
    }
    '/api/admin/templates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/templates/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/templates/index.post').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].put').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.post').default>>>>
    }
    '/api/admissions/appointments/calendar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/appointments/calendar.get').default>>>>
    }
    '/api/admissions/appointments': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/appointments/index.post').default>>>>
    }
    '/api/admissions/companies': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/companies/index.post').default>>>>
    }
    '/api/admissions/companies/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/companies/search.get').default>>>>
    }
    '/api/admissions/doctors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/doctors.get').default>>>>
    }
    '/api/admissions/patients/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/patients/[id].get').default>>>>
    }
    '/api/admissions/patients': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/patients/index.post').default>>>>
    }
    '/api/admissions/patients/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/patients/search.get').default>>>>
    }
    '/api/admissions/protocols': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/protocols.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admissions/protocols.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}