// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/12/2025, 16:44:57
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/plugins/**/*.{js,ts,mjs}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/composables/**/*.{js,ts,mjs}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/utils/**/*.{js,ts,mjs}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/UNIVERSIDAD/10 - CICLO/ING_SOFTWARE II/SEMANA_15/seguridadSalud/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;